//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Settings
    {
        public string options { get; set; }
        public int setting_value { get; set; }
    }
}
