//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicles()
        {
            this.Vehicle_Service = new ObservableListSource<Vehicle_Service>();
            this.Vehicles_Breakdowns = new ObservableListSource<Vehicles_Breakdowns>();
            this.Vehicles_Images = new ObservableListSource<Vehicles_Images>();
        }
    
        public string manufacturer { get; set; }
        public string model { get; set; }
        public int prod_year { get; set; }
        public string fuel_type { get; set; }
        public string color { get; set; }
        public string body_type { get; set; }
        public string VIN { get; set; }
        public string registration_num { get; set; }
        public int engine_capacity { get; set; }
        public int engine_power { get; set; }
        public int vehicle_id { get; set; }
        public string user_email { get; set; }
        public bool available { get; set; }
    
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<Vehicle_Service> Vehicle_Service { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<Vehicles_Breakdowns> Vehicles_Breakdowns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<Vehicles_Images> Vehicles_Images { get; set; }
    }
}
