//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle_Service
    {
        public int vehicle_service_id { get; set; }
        public System.DateTime technical_inspection { get; set; }
        public System.DateTime liability_insurance { get; set; }
        public System.DateTime comprehensive_cover { get; set; }
        public int vehicle_id { get; set; }
    
        public virtual Vehicles Vehicles { get; set; }
    }
}
