//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBBD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VFEntities : DbContext
    {
        public VFEntities()
            : base("name=VFEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Vehicle_Service> Vehicle_Service { get; set; }
        public virtual DbSet<Vehicles> Vehicles { get; set; }
        public virtual DbSet<Vehicles_Breakdowns> Vehicles_Breakdowns { get; set; }
        public virtual DbSet<Vehicles_Images> Vehicles_Images { get; set; }
        public virtual DbSet<Manufacturers> Manufacturers { get; set; }
        public virtual DbSet<Models> Models { get; set; }
        public virtual DbSet<Drivers> Drivers { get; set; }
        public virtual DbSet<Vehicles_Routes> Vehicles_Routes { get; set; }
    }
}
